#!/bin/bash

directories=("input" "output" "workflows")

confirm_proceed() {
    read -p "Press y to continue or any other key to cancel: " -n 1 -r
    echo  # Move to a new line

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Continuing..."
    else
        echo "Cancelled."
        exit 1
    fi
}

source .env

function get_overwrite_option {
    # check if --overwrite is provided
    if [ "$1" = "--overwrite" ]; then
        echo "true"
    else
        echo "false"
    fi
}

cd /home/$SERVER_USER/$PROJECT_ROOT_DIR

# Restore data from r2
echo "Backup data to r2..."
overwrite=$(get_overwrite_option $1)
if [ "$overwrite" = "true" ]; then
    echo "Overwrite option provided. This will overwrite the data directory"
    confirm_proceed

    for dir in "${directories[@]}"; do
        echo "Backing up /home/$SERVER_USER/$PROJECT_ROOT_DIR/comfy/$dir..."
        rclone -v sync /home/$SERVER_USER/$PROJECT_ROOT_DIR/comfy/$dir r2:$CLOUDFLARE_BUCKET_NAME/nomad-data/$dir
    done
else
    echo "Overwrite option not provided. This will merge the data directory"
    for dir in "${directories[@]}"; do
        echo "Backing up /home/$SERVER_USER/$PROJECT_ROOT_DIR/comfy/$dir..."
        rclone -v copy /home/$SERVER_USER/$PROJECT_ROOT_DIR/comfy/$dir r2:$CLOUDFLARE_BUCKET_NAME/nomad-data/$dir
    done
fi
rclone