#!/bin/bash

directories=("input" "output" "workflows")

confirm_proceed() {
    read -p "Press y to continue or any other key to cancel: " -n 1 -r
    echo  # Move to a new line

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Continuing..."
    else
        echo "Cancelled."
        exit 1
    fi
}

source .env

cd /home/$SERVER_USER/$PROJECT_ROOT_DIR

# Restore data from r2
echo "Restoring data from r2..."
echo "Caution: This will overwrite the data directory"
echo "Press enter to continue or Ctrl+C to cancel"
confirm_proceed

for dir in "${directories[@]}"; do
    echo "Restoring /home/$SERVER_USER/$PROJECT_ROOT_DIR/comfy/$dir..."
    # create dir if not exist
    mkdir -p /home/$SERVER_USER/$PROJECT_ROOT_DIR/comfy/$dir
    rclone -v copy r2:$CLOUDFLARE_BUCKET_NAME/nomad-data/$dir /home/$SERVER_USER/$PROJECT_ROOT_DIR/comfy/$dir
done

rclone -v copy r2:$CLOUDFLARE_BUCKET_NAME/nomad-data data