#!/bin/bash

source .env

ssh -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_IP "
    if [ ! -d '/home/$SERVER_USER/$PROJECT_ROOT_DIR' ]; then
        echo 'Directory does not exist. Cloning repository...'
        git clone https://github.com/hammashamzah/nomad /home/$SERVER_USER/$PROJECT_ROOT_DIR
    else
        echo 'Directory exists. Pulling latest changes...'
        cd /home/$SERVER_USER/$PROJECT_ROOT_DIR && git pull
    fi
"

# Do chmod for the bash scripts
echo "Change script execute permission..."
ssh -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_IP "cd /home/$SERVER_USER/$PROJECT_ROOT_DIR && chmod +x nomad && chmod +x scripts/*"

echo "Copying .env file to remote server..."
scp -P $SERVER_SSH_PORT .env $SERVER_USER@$SERVER_IP:/home/$SERVER_USER/$PROJECT_ROOT_DIR/.env

echo "Copying files inside links directory to remote server..."
scp -P $SERVER_SSH_PORT -r links $SERVER_USER@$SERVER_IP:/home/$SERVER_USER/$PROJECT_ROOT_DIR

echo "SSHing into remote server..."
ssh -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_IP