#!/bin/bash

source .env
# copy .env file to remote server
echo "Copying .env file to remote server..."
# Clone nomad repository if not exist
ssh -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_IP "git clone https://github.com/hammashamzah/nomad /home/$SERVER_USER/$PROJECT_ROOT_DIR"
echo "SSHing into remote server..."
# Do chmod for the bash scripts
ssh -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_IP "cd /home/$SERVER_USER/$PROJECT_ROOT_DIR && chmod +x nomad && chmod +x scripts/*"
scp -P $SERVER_SSH_PORT .env $SERVER_USER@$SERVER_IP:/home/$SERVER_USER/$PROJECT_ROOT_DIR/.env
ssh -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_IP