#!/bin/bash

source .env

cd /home/$SERVER_USER/$PROJECT_ROOT_DIR

tmux new-session -d -s $PROJECT_ROOT_DIR

# Split the window into two horizontal panes
tmux split-window -h

# Split both the left and right panes vertically
tmux split-window -v
tmux select-pane -t 1
tmux split-window -v

# Run commands in the specified panes

# On the top left pane, run the server (./scripts/start)
tmux select-pane -t 0
tmux send-keys "cd /home/$SERVER_USER/$PROJECT_ROOT_DIR/comfy" C-m
tmux send-keys "./scripts/start" C-m

# On the top right pane, run htop
tmux select-pane -t 1
tmux send-keys "htop" C-m

# On the bottom right pane, run 'watch -n 1 nvidia-smi'
tmux select-pane -t 3
tmux send-keys "watch -n 1 nvidia-smi" C-m